##################################################################################
#
# Lombok PHP - Write less code!
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright Â©2022-2026 Marcin Orlowski
# @license   https://opensource.org/licenses/LGPL-3.0 LGPL-3.0
# @link      https://github.com/MarcinOrlowski/lombok-php
#
# See https://pre-commit.com for more information about pre-commit.
# See https://pre-commit.com/hooks.html for more available hooks.
#
##################################################################################
# Using pre-commit hooks #
#
# To improve quality of your commit, it's recommended to use "pre-commit" (http://pre-commit.com)
# hooks, that will block  your commits unless all tests pass. This project comes with template
# configuration file `.pre-commit-config.yaml.dist`.
#
# Brief installation instruction:
#
# * Ensure you got Python installed
# * Install pre-commit: `pip install pre-commit`
# * Go to your project source code root directory
# * Copy provided config file template:
#    `cp .pre-commit-config.yaml.dist .pre-commit-config.yaml`
# * Plug hooks into Git pipeline: `pre-commit install`
#
# From now on, pre-commit hooks will be triggered on every commit. To temporarily disable them,
# pass --no-verify as your git argument.
#
# See `pre-commit` official installation docs too: https://pre-commit.com/#install
#
##################################################################################

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
        args: [ '--maxkb=1555550' ]
      # This hook checks yaml files for parseable syntax
      - id: check-yaml
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Prevent addition of new git submodules
      - id: forbid-new-submodules
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
        args: [ '--fix=no' ]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      # Non-executable shell script filename ends in .sh
      - id: script-must-have-extension

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      # Forbid files containing CRLF end-lines to be committed
      - id: forbid-crlf

  - repo: https://github.com/MarcinOrlowski/pre-commit-hooks
    rev: 1.3.0
    hooks:
      # This hook trims trailing whitespace.
      - id: trailing-whitespaces
        exclude_types: [ 'xml' ]
        args: [ '--markdown-linebreak-ext=md', '--fix=yes' ]
      # Ensures that a file is either empty, or ends with one newline
      - id: end-of-file
        exclude_types: [ 'xml' ]
        args: [ '--fix=yes' ]

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      # Runs PHPStan analyser
      - id: php-stan
        files: \.(php)$

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          -
  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      # Runs PHPStan analyser
      - id: php-stan
        files: \.(php)$
